fieldLayouts:
  e6a45b6b-c573-45af-9df1-d91b55fb483f:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 846e30a0-1cab-41f7-acf7-988bd2908697
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42ca441c-21db-4cce-9dd6-74af65fdf470 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1f36e474-47be-4384-9c2c-2a7fc1feb162
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: ce077583-c188-4a8b-84b0-54883bacfaf3
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7178f6c5-4d84-4be2-ae67-46508d1dbcc8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c18ee5bf-3d97-43c5-9e90-108a3e4ee8eb
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 49e319a0-37eb-4ce5-96ad-0636e9beb95b
        userCondition: null
handle: datenschutz
hasTitleField: false
name: Datenschutz
section: 34cd7edf-adb7-4148-93db-b18e5d721a71 # Datenschutz
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
