fieldLayouts:
  242d5aa2-3e18-434d-be14-a89b65f220c9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0af4073e-be0d-4a88-a802-8178252ddbce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2480e5ab-25e5-4372-9a26-e37a1d55bece # Geschichten
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76b7de19-81f7-49cb-86c6-519dca7c5a4a
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 0f99c966-244f-4f4b-ab26-ac13c5b49bc4
        userCondition: null
handle: default
hasTitleField: true
name: Standard
section: 9ddbc4e0-4c02-4dda-ae0f-541f66f6d950 # Sammlungen
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
