fieldLayouts:
  242d5aa2-3e18-434d-be14-a89b65f220c9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 0af4073e-be0d-4a88-a802-8178252ddbce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: c0dde7a1-2b9b-43ef-ab51-42530a991aec
            userCondition: null
          -
            elementCondition: null
            fieldUid: ea544490-5469-4ada-905e-2683e038aa74 # Bild
            instructions: null
            label: Titelbild
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 19756698-9f35-4a96-8e78-7b36a417b6eb
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 2bfb70f4-994d-4e48-93f2-f8654294d7e9 # Verfasser
            instructions: null
            label: 'Herausgeber / Verfasser'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 32edf34b-5de4-483c-af25-ad78b963996e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: f8f886d0-d1ad-4923-afbc-c53e99605708 # Erscheinungsjahr
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 30261e06-2551-42e8-aeb1-dfbde084bf7e
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            type: craft\fieldlayoutelements\HorizontalRule
            uid: fbaf07cc-cbe4-44ad-bd67-0ea73d11dba0
            userCondition: null
          -
            elementCondition: null
            fieldUid: 2480e5ab-25e5-4372-9a26-e37a1d55bece # Geschichten
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76b7de19-81f7-49cb-86c6-519dca7c5a4a
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 0f99c966-244f-4f4b-ab26-ac13c5b49bc4
        userCondition: null
handle: default
hasTitleField: true
name: Standard
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
