fieldLayouts:
  cb61d8f9-dc56-4d39-a6dd-89578753bef6:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 96cdcf98-556a-4d79-8f12-e64296cff246
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: a4115fcc-1941-4286-a95a-929dfa29b161 # Intro
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6a7eb09-2047-4f52-9afc-26022bbedb4a
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: e5ead8d2-e689-417b-a1d4-5b3118ce6b62
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7178f6c5-4d84-4be2-ae67-46508d1dbcc8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f3d47ec-3ce6-4310-9598-023ec567ab6b
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 8eca1559-c533-467f-b46a-174f1c8608bc
        userCondition: null
handle: home
hasTitleField: true
name: Start
section: aa7ac094-9175-46bf-a56b-eaaadd28eb16 # Start
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
