fieldLayouts:
  c4bf0e79-396b-4249-a531-5ea0da063195:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: d5329538-6e79-469a-8af9-0d46fc9b634d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42ca441c-21db-4cce-9dd6-74af65fdf470 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: abdb1370-84a0-4b0e-9482-a0b1900be0e5
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: ab56f5c7-defc-41bd-98e0-5cdb1f2632c3
        userCondition: null
handle: impressum
hasTitleField: false
name: Impressum
section: c5ebf014-54d4-4484-b7aa-0329a1245008 # Impressum
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
