fieldLayouts:
  f835a84a-e433-45a8-9b69-59878ec225ba:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 565e366b-1de4-4967-97a9-f5a9b15802f6
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 09609ea0-b7de-48a9-b460-66c52e396edf # Lyrischer Titel
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dca84457-a068-4914-a18d-d6c4dedefbc7
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: 1d48fdf3-8cb2-4c35-9d8f-0d02bb0038c9
        userCondition: null
handle: klassiker
hasTitleField: true
name: Klassiker
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
