fieldLayouts:
  14c23847-3f04-4702-a7a5-389405ccc552:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 2308bf68-c545-4809-97da-09176e7ba326
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 42ca441c-21db-4cce-9dd6-74af65fdf470 # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 76338275-bbbd-4cac-8376-a778b083240e
            userCondition: null
            warning: null
            width: 100
        name: Inhalt
        uid: a641840e-6467-4d7b-a119-c567f33ad699
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 7178f6c5-4d84-4be2-ae67-46508d1dbcc8 # SEO
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a89e6e76-de20-40fa-a177-f5fa08382513
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 2757b555-9fbb-4b11-bdd3-f354b9842b32
        userCondition: null
handle: kontakt
hasTitleField: false
name: Kontakt
section: f8a6c0a3-3c3d-4d8d-8746-66529b735b79 # Kontakt
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
sortOrder: 1
titleFormat: '{section.name|raw}'
titleTranslationKeyFormat: null
titleTranslationMethod: site
