headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: Example
options:
  code:
    indentSequence: '  '
  htmlSupport:
    allow:
      -
        attributes: true
        classes: true
        styles: true
toolbar:
  - sourceEditing
  - '|'
  - heading
  - '|'
  - blockQuote
  - codeBlock
  - code
  - strikethrough
  - superscript
  - subscript
  - bold
  - italic
  - bulletedList
  - numberedList
  - link
  - insertImage
