columnSuffix: null
contentColumnType: string
fieldGroup: eafb163d-141a-4a25-8213-4922010ea059 # Common
handle: bild
instructions: ''
name: Bild
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:052c597a-1661-44ad-af6a-c27c5cdfa355' # Bilder
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:052c597a-1661-44ad-af6a-c27c5cdfa355' # Bilder
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
