columnSuffix: null
contentColumnType: mediumtext
fieldGroup: 7274ef7d-b972-4149-a0a6-42d17fa8a3f7 # Geschichten
handle: body
instructions: null
name: Body
searchable: true
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: 34b9b5bc-97a7-4c31-94bd-558ab37a8862 # Example
  columnType: mediumtext
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
