columnSuffix: null
contentColumnType: string
handle: collection
instructions: null
name: Sammlung
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources:
    - 'section:9ddbc4e0-4c02-4dda-ae0f-541f66f6d950' # Sammlungen
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
