columnSuffix: null
contentColumnType: text
fieldGroup: 7274ef7d-b972-4149-a0a6-42d17fa8a3f7 # Geschichten
handle: description
instructions: null
name: Kurzbeschreibung
searchable: false
settings:
  availableTransforms: '*'
  availableVolumes: '*'
  ckeConfig: b58ec1a2-59e9-4b66-99c9-497736aa70fd # Default
  columnType: text
  defaultTransform: ''
  enableSourceEditingForNonAdmins: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
