columnSuffix: null
contentColumnType: string(1000)
handle: excerpt
instructions: null
name: Excerpt
searchable: false
settings:
  byteLimit: null
  charLimit: 250
  code: false
  columnType: null
  initialRows: 4
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
