columnSuffix: null
contentColumnType: string
fieldGroup: eafb163d-141a-4a25-8213-4922010ea059 # Common
handle: geschichten
instructions: null
name: Geschichten
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionCondition:
    __assoc__:
      -
        - elementType
        - craft\elements\Entry
      -
        - fieldContext
        - global
      -
        - class
        - craft\elements\conditions\entries\EntryCondition
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:7e9ba3cc-acd2-4baa-ad4a-a0c936316dec' # Geschichten
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
