columnSuffix: null
contentColumnType: string
handle: kategorie
instructions: null
name: Kategorie
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: 1
  localizeRelations: false
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:359d960b-bbd2-4552-9e48-5f69abc91382' # Typ
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
