columnSuffix: null
contentColumnType: string
fieldGroup: eafb163d-141a-4a25-8213-4922010ea059 # Common
handle: kategorie
instructions: ''
name: Kategorie
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: ''
  limit: null
  localizeRelations: false
  selectionLabel: ''
  showSiteMenu: false
  source: 'group:359d960b-bbd2-4552-9e48-5f69abc91382' # Klassiker
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
