columnSuffix: null
contentColumnType: string
fieldGroup: eafb163d-141a-4a25-8213-4922010ea059 # Common
handle: kategorie
instructions: null
name: Kategorie
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: true
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:359d960b-bbd2-4552-9e48-5f69abc91382' # Typ
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
