columnSuffix: null
contentColumnType: string
handle: topic
instructions: null
name: Thema
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: true
  source: 'group:01fc6e9c-72dc-441d-b489-218d8a4b06c6' # Thema
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
