columnSuffix: null
contentColumnType: string
handle: verfasser
instructions: null
name: Verfasser
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: 1
  minRelations: 1
  selectionLabel: null
  showSiteMenu: true
  sources:
    - 'section:da051380-6a4c-422f-8f83-26f2ff828f94' # Verfasser
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
