dateModified: 1744963194
elementSources:
  craft\elements\Entry:
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - link
      type: native
    -
      key: singles
      type: native
    -
      heading: Kanäle
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:da051380-6a4c-422f-8f83-26f2ff828f94' # Verfasser
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      heading: Geschichten
      type: heading
    -
      defaultSort:
        - postDate
        - desc
      disabled: false
      key: 'section:7e9ba3cc-acd2-4baa-ad4a-a0c936316dec' # Geschichten
      tableAttributes:
        - postDate
        - expiryDate
        - link
      type: native
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 24932174-a850-49a9-85c4-05b0c950ffe8
            values:
              - 7e9ba3cc-acd2-4baa-ad4a-a0c936316dec # Geschichten
          -
            class: craft\elements\conditions\RelatedToConditionRule
            elementId: '2003'
            elementType: craft\elements\Entry
            uid: 4cc7a90f-c3ca-4ccf-8bac-cf281acd1297
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:c20a14db-f548-4a10-8760-4a62121373c5'
      label: '– Brüder Grimm'
      tableAttributes:
        - 'field:ea544490-5469-4ada-905e-2683e038aa74' # Bild
        - 'field:c30a509f-3a8c-4422-9e5a-5a19518cad94' # Klassiker
        - 'field:d566da45-e6de-4333-84d1-d9ed9a1d31fd' # Kategorie
        - 'field:6e7f4ada-5896-4954-a687-b65570ccfd15' # Readtime
        - 'field:3bbde26d-60d2-468f-b648-991c3603e80c' # Excerpt
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 46295ddc-c649-4b0f-8378-955193d631a2
            values:
              - 7e9ba3cc-acd2-4baa-ad4a-a0c936316dec # Geschichten
          -
            class: craft\elements\conditions\RelatedToConditionRule
            elementId: '2005'
            elementType: craft\elements\Entry
            uid: 738b18ad-9f26-4c7d-8247-57c9605569b0
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:2b01d5ed-1740-4622-96ea-d5768a05ce06'
      label: '- Hans Christian Andersen'
      tableAttributes:
        - 'field:c30a509f-3a8c-4422-9e5a-5a19518cad94' # Klassiker
        - 'field:d566da45-e6de-4333-84d1-d9ed9a1d31fd' # Kategorie
        - 'field:6e7f4ada-5896-4954-a687-b65570ccfd15' # Readtime
        - 'field:3bbde26d-60d2-468f-b648-991c3603e80c' # Excerpt
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 5aa78a26-3a8c-4bd1-9826-3707a28de01e
            values:
              - 7e9ba3cc-acd2-4baa-ad4a-a0c936316dec # Geschichten
          -
            class: craft\elements\conditions\RelatedToConditionRule
            elementId: '2015'
            elementType: craft\elements\Entry
            uid: 327acbcc-7e63-4323-93e0-0100bf53454a
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:ca716e0b-3dc1-4928-bed0-363ef1f93dd2'
      label: '- Wilhelm Hauff'
      tableAttributes:
        - 'field:c30a509f-3a8c-4422-9e5a-5a19518cad94' # Klassiker
        - 'field:d566da45-e6de-4333-84d1-d9ed9a1d31fd' # Kategorie
        - 'field:6e7f4ada-5896-4954-a687-b65570ccfd15' # Readtime
        - 'field:3bbde26d-60d2-468f-b648-991c3603e80c' # Excerpt
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 5be2fc4a-8f15-4fba-a9c2-df933019f38b
            values:
              - 7e9ba3cc-acd2-4baa-ad4a-a0c936316dec # Geschichten
          -
            class: craft\elements\conditions\RelatedToConditionRule
            elementId: '2013'
            elementType: craft\elements\Entry
            uid: c70eccf0-d3be-4a2c-8eee-1dbc97acd566
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:1966dfcc-609b-423e-aeab-9f3a857db625'
      label: '– Richard von Volkmann-Leander'
      tableAttributes:
        - 'field:c30a509f-3a8c-4422-9e5a-5a19518cad94' # Klassiker
        - 'field:d566da45-e6de-4333-84d1-d9ed9a1d31fd' # Kategorie
        - 'field:6e7f4ada-5896-4954-a687-b65570ccfd15' # Readtime
        - 'field:3bbde26d-60d2-468f-b648-991c3603e80c' # Excerpt
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: b0c0eaf8-f86a-43ff-87aa-fd3348f7d4f8
            values:
              - 7e9ba3cc-acd2-4baa-ad4a-a0c936316dec # Geschichten
          -
            class: craft\elements\conditions\RelatedToConditionRule
            elementId: '2011'
            elementType: craft\elements\Entry
            uid: 837540cf-5b4d-4efd-8701-5ea9c30e1b93
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:ab0e55c9-af16-4270-a1b1-eefc30fc8880'
      label: '– Ludwig Bechstein'
      tableAttributes:
        - 'field:c30a509f-3a8c-4422-9e5a-5a19518cad94' # Klassiker
        - 'field:d566da45-e6de-4333-84d1-d9ed9a1d31fd' # Kategorie
        - 'field:6e7f4ada-5896-4954-a687-b65570ccfd15' # Readtime
        - 'field:3bbde26d-60d2-468f-b648-991c3603e80c' # Excerpt
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 0ed7e354-f4bb-4c76-89cb-3adc36aa00b9
            values:
              - 7e9ba3cc-acd2-4baa-ad4a-a0c936316dec # Geschichten
          -
            class: craft\elements\conditions\RelatedToConditionRule
            elementId: '2009'
            elementType: craft\elements\Entry
            uid: 9404d6e1-766a-4221-9ea0-74325a0ae102
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:caf95646-64a8-4083-b865-a31930e1c8ad'
      label: '– Josef Haltrich'
      tableAttributes:
        - 'field:c30a509f-3a8c-4422-9e5a-5a19518cad94' # Klassiker
        - 'field:d566da45-e6de-4333-84d1-d9ed9a1d31fd' # Kategorie
        - 'field:6e7f4ada-5896-4954-a687-b65570ccfd15' # Readtime
        - 'field:3bbde26d-60d2-468f-b648-991c3603e80c' # Excerpt
      type: custom
    -
      condition:
        class: craft\elements\conditions\entries\EntryCondition
        conditionRules:
          -
            class: craft\elements\conditions\entries\SectionConditionRule
            operator: in
            uid: 73caf79c-89a5-4689-bc75-5ec4adfd5f73
            values:
              - 7e9ba3cc-acd2-4baa-ad4a-a0c936316dec # Geschichten
          -
            class: craft\elements\conditions\RelatedToConditionRule
            elementId: '2007'
            elementType: craft\elements\Entry
            uid: f5817200-f507-4139-8a43-27c551c19db5
        elementType: craft\elements\Entry
        fieldContext: global
      defaultSort:
        - title
        - asc
      key: 'custom:b0400057-a531-4d1b-96e2-aef54bbe36fe'
      label: '– Johann Wilhelm Wolf'
      tableAttributes:
        - 'field:c30a509f-3a8c-4422-9e5a-5a19518cad94' # Klassiker
        - 'field:d566da45-e6de-4333-84d1-d9ed9a1d31fd' # Kategorie
        - 'field:6e7f4ada-5896-4954-a687-b65570ccfd15' # Readtime
        - 'field:3bbde26d-60d2-468f-b648-991c3603e80c' # Excerpt
      type: custom
    -
      heading: ''
      type: heading
    -
      key: 'section:9ddbc4e0-4c02-4dda-ae0f-541f66f6d950' # Sammlungen
      type: native
email:
  fromEmail: me@marcusscheller.com
  fromName: 'Armin & Artur'
  transportType: craft\mail\transportadapters\Sendmail
fs:
  bilder:
    hasUrls: true
    name: Bilder
    settings:
      path: '@webroot/bilder'
    type: craft\fs\Local
    url: '@web/bilder'
meta:
  __names__:
    0cb827ea-5f8e-47dd-99f3-c5dcfe109904: Schlagwörter # Schlagwörter
    0cb29916-8e38-4a34-9080-9abeaf29e4dc: 'Märchen unter 10 Minuten' # Märchen unter 10 Minuten
    01fc6e9c-72dc-441d-b489-218d8a4b06c6: Thema # Thema
    02ab3a5d-5422-48bc-8189-ae183eaa67a5: Thema # Thema
    2b8dd1f0-4052-42e4-8538-cae0142ec6d5: 'KHM Nummerierung' # KHM Nummerierung
    2bfb70f4-994d-4e48-93f2-f8654294d7e9: Verfasser # Verfasser
    3bbde26d-60d2-468f-b648-991c3603e80c: Excerpt # Excerpt
    6e7f4ada-5896-4954-a687-b65570ccfd15: Readtime # Readtime
    7a3c7af4-e299-43c6-87a8-b78184c70698: Standard # Standard
    7a858b5b-63e8-46b5-b58c-2d610aa94193: Sammlung # Sammlung
    7e9ba3cc-acd2-4baa-ad4a-a0c936316dec: Geschichten # Geschichten
    7f3606d2-88a5-4912-a779-e0a26737e261: Bild-Alttext # Bild-Alttext
    08cc6be7-aaba-4e69-9add-118341b6171b: Datenschutz # Datenschutz
    8e4dd4d0-be39-48db-b977-dc2bf7655579: Geschichte # Geschichte
    9ddbc4e0-4c02-4dda-ae0f-541f66f6d950: Sammlungen # Sammlungen
    13c8564a-f8d2-469e-8154-599bf6ef3455: 'Märchen des Tages' # Märchen des Tages
    14a2cc67-f120-47c2-9e90-c6bf26e83377: Klassiker # Klassiker
    19a8c7f5-af22-411d-b853-b7e733678b85: Bildunterschrift # Bildunterschrift
    34cd7edf-adb7-4148-93db-b18e5d721a71: Datenschutz # Datenschutz
    42ca441c-21db-4cce-9dd6-74af65fdf470: Body # Body
    052c597a-1661-44ad-af6a-c27c5cdfa355: Bilder # Bilder
    094fd7f3-8e76-4a20-9392-9f066c39a615: 'MJ Prompt' # MJ Prompt
    359d960b-bbd2-4552-9e48-5f69abc91382: Typ # Typ
    619dd491-28e5-43a2-892b-5e7a6a713275: Standard # Standard
    706dd587-cd73-45b9-bfd0-fb3cd5604640: Thema # Thema
    829d7233-deb8-4544-bce0-f8761be6d04c: Klassifikation # Klassifikation
    892cd95a-b813-4d5d-a5e6-5e20e3db19a5: Home # Home
    2480e5ab-25e5-4372-9a26-e37a1d55bece: Geschichten # Geschichten
    5380e350-b359-48a0-82ad-3903b3056fa3: 'Märchen unter 10 Minuten' # Märchen unter 10 Minuten
    6110af5f-6541-462e-9399-8ecbb64ba158: Kontakt # Kontakt
    7178f6c5-4d84-4be2-ae67-46508d1dbcc8: SEO # SEO
    7274ef7d-b972-4149-a0a6-42d17fa8a3f7: Geschichten # Geschichten
    9590d88e-4c68-4ee2-bf34-09bbb3fc8833: 'Armin & Artur' # Armin & Artur
    09609ea0-b7de-48a9-b460-66c52e396edf: 'Lyrischer Titel' # Lyrischer Titel
    83262edd-7265-48b8-adcd-1a1cec0c51a8: 'Armin & Artur' # Armin & Artur
    991163cd-0f18-4991-8e36-4272130a111f: Impressum # Impressum
    a4115fcc-1941-4286-a95a-929dfa29b161: Intro # Intro
    aa7ac094-9175-46bf-a56b-eaaadd28eb16: Start # Start
    b498f081-a398-4f88-b9b7-25afbf7a44f9: 'Public Schema' # Public Schema
    bc88ad51-fa04-4adb-a0f2-365b8a1b9179: Klassiker # Klassiker
    bc114695-97bc-44c6-a0de-c5152243cd6e: Kurzbeschreibung # Kurzbeschreibung
    c5ebf014-54d4-4484-b7aa-0329a1245008: Impressum # Impressum
    c30a509f-3a8c-4422-9e5a-5a19518cad94: Klassiker # Klassiker
    d566da45-e6de-4333-84d1-d9ed9a1d31fd: Kategorie # Kategorie
    d9146733-1222-4c11-a9d4-326fa757b7e3: Bild-Urheber # Bild-Urheber
    da051380-6a4c-422f-8f83-26f2ff828f94: Verfasser # Verfasser
    ea544490-5469-4ada-905e-2683e038aa74: Bild # Bild
    eafb163d-141a-4a25-8213-4922010ea059: Common # Common
    f8a6c0a3-3c3d-4d8d-8746-66529b735b79: Kontakt # Kontakt
    f8a87993-286a-442c-95f6-d708ba6fc31d: Start # Start
    f8f886d0-d1ad-4923-afbc-c53e99605708: Erscheinungsjahr # Erscheinungsjahr
plugins:
  assetrev:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  blitz-recommendations:
    edition: standard
    enabled: true
    schemaVersion: 2.2.0
  cookies:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 5.1.1
  image-toolbox:
    edition: lite
    enabled: true
    schemaVersion: 1.0.0
  logs:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
  preparse-field:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
  redactor:
    edition: standard
    enabled: true
    schemaVersion: 2.3.0
  redactor-custom-styles:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  redirect:
    edition: standard
    enabled: true
    schemaVersion: 1.0.5
  reverserelations:
    edition: standard
    enabled: true
    schemaVersion: 1.0.1
  seo:
    edition: standard
    enabled: false
    schemaVersion: 3.2.0
  seomatic:
    edition: standard
    enabled: true
    licenseKey: 2XM83J1QNBYWNT37HNOUWCVW
    schemaVersion: 3.0.12
    settings:
      addHrefLang: true
      addPaginatedHreflang: true
      addXDefaultHrefLang: true
      alwaysIncludeCanonicalUrls: false
      cpTitlePrefix: '⚙ '
      cspNonce: ''
      cspScriptSrcPolicies:
        -
          __assoc__:
            -
              - policy
              - '''self'''
      devModeCpTitlePrefix: '&#x1f6a7;⚙ '
      devModeTitlePrefix: '&#x1f6a7; '
      displayAnalysisSidebar: true
      displayPreviewSidebar: true
      enableDebugToolbarPanel: true
      enableJsonLdEndpoint: false
      enableMetaContainerEndpoint: false
      enableSeoFileLinkEndpoint: false
      environment: live
      excludeNonCanonicalUrls: false
      generatorEnabled: true
      headersEnabled: true
      includeHomepageInBreadcrumbs: true
      lowercaseCanonicalUrl: true
      manuallySetEnvironment: false
      maxDescriptionLength: 155
      maxTitleLength: 70
      metaCacheDuration: 0
      pluginName: SEOmatic
      regenerateSitemapsAutomatically: true
      renderEnabled: true
      separatorChar: '|'
      sidebarDisplayPreviewTypes:
        - google
        - twitter
        - facebook
        - pinterest
      siteGroupsSeparate: true
      siteUrlOverride: ''
      sitemapsEnabled: true
      socialMediaPreviewTarget: true
      submitSitemaps: true
      truncateDescriptionTags: true
      truncateTitleTags: true
  tag-manager:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  venveo-bulk-edit:
    edition: standard
    enabled: true
    schemaVersion: 1.1.0
  wordsmith:
    edition: standard
    enabled: true
    schemaVersion: 0.0.0.0
system:
  edition: solo
  live: true
  name: 'Armin & Artur'
  retryDuration: null
  schemaVersion: 4.15.0.0
  timeZone: Europe/Berlin
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
