defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 08cc6be7-aaba-4e69-9add-118341b6171b # Datenschutz
handle: datenschutz
maxAuthors: 1
minAuthors: 1
name: Datenschutz
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  9590d88e-4c68-4ee2-bf34-09bbb3fc8833: # Armin & Artur
    enabledByDefault: true
    hasUrls: true
    template: page.twig
    uriFormat: datenschutz
type: single
