defaultPlacement: end
enableVersioning: true
handle: klassiker
name: Klassiker
propagationMethod: all
siteSettings:
  9590d88e-4c68-4ee2-bf34-09bbb3fc8833: # Armin & Artur
    enabledByDefault: true
    hasUrls: true
    template: klassiker.twig
    uriFormat: klassiker-die-schönsten-märchen
type: single
