defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 6110af5f-6541-462e-9399-8ecbb64ba158 # Kontakt
handle: kontakt
maxAuthors: 1
minAuthors: 1
name: Kontakt
previewTargets:
  -
    label: 'Primary entry page'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  9590d88e-4c68-4ee2-bf34-09bbb3fc8833: # Armin & Artur
    enabledByDefault: true
    hasUrls: true
    template: page.twig
    uriFormat: kontakt
type: single
