defaultPlacement: end
enableVersioning: true
handle: shorts
name: 'Märchen unter 10 Minuten'
propagationMethod: all
siteSettings:
  9590d88e-4c68-4ee2-bf34-09bbb3fc8833: # Armin & Artur
    enabledByDefault: true
    hasUrls: true
    template: maerchen-unter-10-minuten.twig
    uriFormat: maerchen-unter-10-minuten
type: single
